### PR TITLE
feat(yaml, helm) allow condition to check only for a key (and not its value) + refactoring

### LINKED ISSUE #289: Feature Request [Resource "YAML"] allow condition to only check for existence of a key (and not the value)
**Is your feature request related to a problem? Please describe.**

Let's consider the following YAML manifest: https://github.com/jenkins-infra/jenkins-infra/blob/958091069665a88a32a72e154e644d55f54e1b71/updatecli/weekly.d/buildmaster-tools.yaml#L70

I would like to add a condition that would check for the existence of the key in the YAML file.

The rationale is that as soon as #60 is implemented, then the execution would not fail when the key does not exist, leading to false positive (the key would be created and updatecli would report a success while the user would want to be notifieed of this as a failure because the YAML was changed recently but not updatecli manifest).

**Describe the solution you'd like**

Adding a new attribute `keyOnly` only available on the condition of kind "YAML", that would ignore the value and only check for the existence of the key.

**Describe alternatives you've considered**

- Using a shell condition with the command `yq`

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by dduportal**
Fix #289

This PR introduces the following changes to the YAML and `helm` resources:

* [yaml] allow condition to check only for a key (and not its value) (#289)
* [yaml] fix a validation error when file path started with the prefix `file://`
* [yaml] refactor to use the same naming conventions as others like `aws/ami` or `shell`, and
* [helm] rename package to follow golang convention (no need for subpackage if there is only one)
* [helm] introduce a `New()` method to have a constructor.
* [yaml] ensure that private attributes are used (decoupled from Helm resource)
* Add examples

## Test

To test this pull request, you can run the following commands:

```shell
go build -o ./dist/updatecli
```

### CODE REVIEW

**Comment by dduportal** [comment]
@olblak I propose to add this to the `0.18.0` milestone, WDYT?

**Comment by olblak** [comment]
> @olblak I propose to add this to the `0.18.0` milestone, WDYT?

It sounds good to me but as a reminder, we decided to assign issues to milestone and not pull request

**Comment by dduportal** [comment]
> > @olblak I propose to add this to the 0.18.0 milestone, WDYT?
> It sounds good to me but as a reminder, we decided to assign issues to milestone and not pull request

Sorry, I thought I was commenting in the issue. Good thing that you point it out to me :)

**Review by olblak — APPROVED** [review]
Thanks for the refactoring as well

**Pull request merged**
