### PR TITLE
chore: replace hardcoded ⚠

### LINKED ISSUE #489: Replace remaining hardcoded output symbols by `result.*`
Ex: https://github.com/updatecli/updatecli/blob/2279c083b2e40ef091d836d7b2195b91bf8aa4b0/pkg/core/pipeline/target/main.go#L152

### PR DESCRIPTION
**Pull request by lemeurherve**
# Title

Fix #489

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

### CODE REVIEW

**Review by olblak — APPROVED** [review]
Oops :p

**Review by dduportal — APPROVED** [review]
thanks !

**Comment by lemeurherve** [comment]
3 hours already... That a bit long for these checks isn't it? 😛

**Comment by olblak** [comment]
Let's hope that this time check will pass

**Pull request merged**
