### PR TITLE
Add use title for auto merge

### LINKED ISSUE #776: Feature Request: shell allow custom commit message
### Is your feature request related to a problem?

https://github.com/updatecli/updatecli/blob/9e8b7ee5cfd2a4ba12178bed2d01eb25501d6e97/pkg/plugins/resources/shell/target.go#L75

Would be nice to replace the default commit message.

Especially with squash method it chooses the wrong commit message, would prefer the PR title over shell command:
https://github.com/jenkinsci/bom/commit/ba1fe6775643d834aa27ef4a9c795ca60f19fc57

### Solution you'd like

Allow override of message, it would be nice to customize the message as the default is kinda 💩 and in the manifest we can write the exact commit message that we expect.

### Alternatives you've considered

Update Squash method to pick PR title instead of commit message.

https://pkg.go.dev/github.com/shurcool/githubv4#EnablePullRequestAutoMergeInput

We should add the `CommitHeadline` and `CommitBody`

```go
type EnablePullRequestAutoMergeInput struct {
	// ID of the pull request to enable auto-merge on. (Required.)
	PullRequest[ID](https://pkg.go.dev/github.com/shurcool/githubv4#ID) ID `json:"pullRequestId"`

	// Commit headline to use for the commit when the PR is mergable; if omitted, a default message will be used. (Optional.)
	CommitHeadline *[String](https://pkg.go.dev/github.com/shurcool/githubv4#String) `json:"commitHeadline,omitempty"`
	// Commit body to use for the commit when the PR is mergable; if omitted, a default message will be used. (Optional.)
	CommitBody *[String](https://pkg.go.dev/github.com/shurcool/githubv4#String) `json:"commitBody,omitempty"`
	// The merge method to use. If omitted, defaults to 'MERGE'. (Optional.)
	MergeMethod *[PullRequestMergeMethod](https://pkg.go.dev/github.com/shurcool/githubv4#PullRequestMergeMethod) `json:"mergeMethod,omitempty"`
	// The email address to associate with this merge. (Optional.)
	AuthorEmail *[String](https://pkg.go.dev/github.com/shurcool/githubv4#String) `json:"authorEmail,omitempty"`
	// A unique identifier for the client performing the mutation. (Optional.)
	ClientMutationID *[String](https://pkg.go.dev/github.com/shurcool/githubv4#String) `json:"clientMutationId,omitempty"`
}
```

https://github.com/updatecli/updatecli/blob/eb441959579e3b061f458b013c2b6a9a5fe9c755/pkg/plugins/scms/github/pullrequest.go#L317-L319

### Anything else?

Feedback would be appreciated, so I could potentially open a fix for one or both solutions.

### PR DESCRIPTION
**Pull request by jetersen**
Automerge by default assumes commit message, and since some of the sources are not able to customize their commit messages this is the most obvious way to get the desired merge message with automerge.

Fix #776

## Test

🤷‍♂️ Could not find a test for this area of the code, feel free to point me to it 😅 

## Additional Information

Allow it to behave like user would make pull request with auto merge for squash and rebase commit messages.

### CODE REVIEW

**Comment by olblak** [comment]
> man_shrugging Could not find a test for this area of the code, feel free to point me to it sweat_smile

Well I missing quite a lot of test :) 

> since some of the sources are not able to customize their commit

You should be able to customize your commit using https://www.updatecli.io/docs/plugins/scm/git/#_commitmessage

I am currently working on gitea documentationm so I'll also cleanup a bit the git and github doc which is a bit outdated

**Comment by jetersen** [comment]
Well I want to customize the shell commit message which does not seem possible and I don't want to customize my commit message on `scm` object as I suspect it does not support templating from for instance `{{ source "plugin" }}`

**Comment by jetersen** [comment]
as suspected after some testing, updatecli has undesired results:

https://github.com/jetersen/bom/commit/338239047677eda4d55f1893dbfe58463d1777e2
https://github.com/jetersen/bom/pull/2

I would love to get rid of the mandatory `chore` really ought to be optional :)

Also get rid of the mandatory `...` shorting. Let the user decide what is too long.
Still includes the shell command which I care little for 😅

**Comment by jetersen** [comment]
At least this PR would fix my immediate issue :)

**Comment by olblak** [comment]
> as suspected after some testing, updatecli has undesired results:

that's sounds like a regression :) 

> Also get rid of the mandatory ... shorting. Let the user decide what is too long.

Well I don't have strong opinion, I decided to stick to the 72 characters

> At least this PR would fix my immediate issue. Potentially I should make sure that the title is expanded for source sweat_smile

This PR is really useful, and I will probably start using it as well.

**Review by olblak — APPROVED** [review]
I didn't test it but I guess you did :)

**Comment by olblak** [comment]
I'll trigger the release 0.29.0 tomorrow

**Comment by jetersen** [comment]
After some testing, this does not work at least the way it was intended:

https://github.com/jetersen-cloud/updatecli-test/commit/9cf5bf824623336fca705bffbc9f2b3086470711

**Comment by jetersen** [comment]
fixes #784

**Pull request merged**
