### PR TITLE
feat(temurin): introduces condition to check for Adoptium releases existence

### LINKED ISSUE #2915: Feature Request: Temurin conditions
### Is your feature request related to a problem?

In https://github.com/updatecli/updatecli/issues/2839, the author tried to use a condition of type `temurin` which is not implemented as per https://www.updatecli.io/docs/plugins/resource/temurin/

Capture d’écran 2024-10-27 à 09 02 38

### Solution you'd like

Support of a condition to check if a given version, installer_url, checksum_url or signature_url exists or not.

Please note that using a source of type `temurin` and then checking its existence with a condition makes no sense (since both should use the same API endpoints and code).

The added value would be in specifying a collection of platform to check all at once.

Let's check the following use case as an example (inspired from the attempt at):

```
sources:
  # The source is expected to show a version to be passed to a Dockerfile build arg
  # example of expected source result: '17.0.13+11`
  lastTemurin21Version:
    kind: temurin
    name: Get the latest Adoptium JDK21 version via the API
    spec:
      featureversion: 21
    transformers:
      - trimprefix: "jdk-"
      - replacer:
          from: +
          to: _

# Check if the "latest version", which is implicitly for x64 Linux, exists for all provided architectures
conditions:
  checkTemurinAlpineRelease:
    name: Check if the "<lastTemurin21Version>" is available for all custom Linux architectures
    kind: temurin
    sourceid: lastTemurin21Version
    spec:
      featureversion: 21
      architectures:
        - x64
        - s390x
```

I wonder about the pertinence of the `architectures` (plural form) as we'll quickly need to specify `os` and other filter soon, creating a matrix hard to maintain.

WDYT about adding a specify use case around the word "platform" which maps to usual Docker specifier but to **none** of the Temurin API keywords: less risk of confusion then.

Example (condition only!):

```yaml
# Check if the "latest version", which is implicitly for x64 Linux, exists for all provided architectures
conditions:
  checkTemurinAlpineRelease:
    name: Check if the "<lastTemurin21Version>" is available for all custom Linux architectures
    kind: temurin
    sourceid: lastTemurin21Version
    spec:
      featureversion: 21
      platforms:
        - linux/x64
        - windows/x64
        - alpine/arm64
```

### Alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dduportal**
Fix #2915

This PR introduces a new condition for the resource type `temurin`

- Supports specific version through source input or `spec`
- Introduces a condition-only keyword: `platforms` to check for multiple combinations of CPU Architecture and Operating Systems.

Associated documentation PR: https://github.com/updatecli/website/pull/1874

## Test

To test this pull request, you can run the following commands:

```shell
cd pkg/plugins/resources/temurin/
go test
```

### CODE REVIEW

**Comment by gounthar** [comment]
Thanks a lot! 👍

**Comment by dduportal** [comment]
Ready to review!

**Comment by gounthar** [comment]
I may have done something stupid, but here are my [manifest](https://github.com/gounthar/docker/blob/fca37af49c6816e98bf303cd02962dcee01f4f37/updatecli/updatecli.d/jdk21.yaml) and my output:
```
---
name: Bump JDK21 version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastTemurin21Version:
    kind: temurin
    name: Get the latest Adoptium JDK21 version via the API
    spec:
      featureversion: 21
    transformers:
      - trimprefix: "jdk-"
      - replacer:
          from: +
          to: _

conditions:
  checkTemurinAllReleases:
    name: Check if the "<lastTemurin21Version>" is available for all platforms
    kind: temurin
    spec:
      featureversion: 21
      platforms:
        - alpine-linux/x64
        - alpine-linux/aarch64
        - linux/x64
        - linux/aarch64
        - linux/ppc64le
        - linux/s390x
        - linux/riscv64
        - windows/x64
        - windows/aarch64

targets:
  ## Global config files
  setJDK21VersionDockerBake:
    name: "Bump JDK21 version for Linux images in the docker-bake.hcl file"
    kind: hcl
    spec:
      file: docker-bake.hcl
      path: variable.JAVA21_VERSION.default
    scmid: default
  setJDK21VersionWindowsDockerCompose:
    name: "Bump JDK21 version in build-windows.yaml"
    kind: yaml
    spec:
      files:
        - build-windows.yaml
      key: $.services.jdk21.build.args.JAVA_VERSION
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump JDK21 version to {{ source "lastTemurin21Version" }}
    spec:
      labels:
        - dependencies
        - jdk21

```
```
updatecli diff --debug --config ./updatecli/updatecli.d/jdk21.yaml --values ./updatecli/v
alues.github-action.yaml 2>&1


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "./updatecli/updatecli.d/jdk21.yaml"
DEBUG: pipelineid undefined, we'll try to generate one
DEBUG: using pipeline name to generate the pipelineid

SCM repository retrieved: 1
DEBUG: cloning git repository: https://github.com/gounthar/docker.git in /tmp/updatecli/github/gounthar/docker
Enumerating objects: 12504, done.
Counting objects: 100% (445/445), done.
Compressing objects: 100% (163/163), done.
Total 12504 (delta 189), reused 384 (delta 144), pack-reused 12059 (from 1)
DEBUG: Fetching remote branches for resetting local ones


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



######################
# BUMP JDK21 VERSION #
######################

source: source#lastTemurin21Version
---------------------------
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/architectures"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[BYPASS] Cf-Ray:[8e56ec7f2fff2a1f-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 20 Nov 2024 08:03:30 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-mqqqx]] 0xc00175b980 -1 [] false true map[] 0xc000976280 0xc000ee7380}
DEBUG: [temurin] API client got the following Location header value: "".
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/operating_systems"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[BYPASS] Cf-Ray:[8e56ec818a4d2a1f-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 20 Nov 2024 08:03:30 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-jwmm4]] 0xc00175be60 -1 [] false true map[] 0xc00022f680 0xc000ee7380}
DEBUG: [temurin] API client got the following Location header value: "".
DEBUG: [temurin] using API endpoint "/info/release_names?heap_size=normal&image_type=jdk&page=0&page_size=10&project=jdk&release_type=ga&architecture=x64&os=linux&semver=true&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse&version=%2821.0.0%2C+22.0.0%5D"
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/info/release_names?heap_size=normal&image_type=jdk&page=0&page_size=10&project=jdk&release_type=ga&architecture=x64&os=linux&semver=true&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse&version=%2821.0.0%2C+22.0.0%5D"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=86400] Cache-Control:[public, max-age=14400, no-transform, s-maxage=120] Cf-Cache-Status:[EXPIRED] Cf-Ray:[8e56ec83fc6e2a1f-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 20 Nov 2024 08:03:30 GMT] Etag:[5675ee6aadd136d8c1cde2a2f22a9205] Last-Modified:[Tue, 19 Nov 2024 19:52:00 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-jwmm4]] 0xc001b7a300 -1 [] false true map[] 0xc00022fb80 0xc000ee7380}
DEBUG: [temurin] API client got the following Location header value: "".
✔ [temurin] found version "jdk-21.0.5+11"
[transformers]
✔ Result correctly transformed from "jdk-21.0.5+11" to "21.0.5+11"
✔ Result correctly transformed from "21.0.5+11" to "21.0.5_11"


CHANGELOG:
----------
https://adoptium.net/temurin/release-notes/?version=jdk-21.0.5+11


condition: condition#checkTemurinAllReleases
---------------------------------
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/architectures"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[BYPASS] Cf-Ray:[8e56ec866f332a1f-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 20 Nov 2024 08:03:31 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-mqqqx]] 0xc001b7b680 -1 [] false true map[] 0xc0009a6500 0xc000ee7380}
DEBUG: [temurin] API client got the following Location header value: "".
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/operating_systems"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[BYPASS] Cf-Ray:[8e56ec871fe82a1f-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 20 Nov 2024 08:03:31 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-lc7wj]] 0xc001b7ba10 -1 [] false true map[] 0xc0009a6780 0xc000ee7380}
DEBUG: [temurin] API client got the following Location header value: "".
[temurin] using specific version (`spec.SpecificVersion`) from source value "21.0.5_11". Set `disablesourceinput` to true to avoid this behavior.
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/version/21.0.5_11"...
DEBUG: [temurin] API client returned the following response:
&{400 Bad Request 400 HTTP/2.0 2 0 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[BYPASS] Cf-Ray:[8e56ec87d89c2a1f-CDG] Content-Encoding:[identity] Content-Length:[0] Date:[Wed, 20 Nov 2024 08:03:31 GMT] Server:[cloudflare] Speculation-Rules:["/cdn-cgi/speculation"] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-7c6c5f5476-jwmm4]] {} 0 [] false false map[] 0xc0009a7400 0xc000ee7380}
ERROR: something went wrong while parsing the version "21.0.5_11" with the Temurin API available operating systems "[temurin] Caught HTTP error 400 from the API.\n"

target: target#setJDK21VersionDockerBake
--------------------------------
DEBUG: Skipping target["target#setJDK21VersionDockerBake"] because of dependsOn conditions

target: target#setJDK21VersionWindowsDockerCompose
------------------------------------------
DEBUG: Skipping target["target#setJDK21VersionWindowsDockerCompose"] because of dependsOn conditions


ACTIONS
========

DEBUG: 2 target(s) (setJDK21VersionDockerBake,setJDK21VersionWindowsDockerCompose) skipped for action "default"

=============================

SUMMARY:



- Bump JDK21 version:
        Source:
                ✔ [lastTemurin21Version] Get the latest Adoptium JDK21 version via the API
        Condition:
                ✗ [checkTemurinAllReleases] Check if the "<lastTemurin21Version>" is available for all platforms
        Target:
                - [setJDK21VersionDockerBake]
                - [setJDK21VersionWindowsDockerCompose]


Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    1
  * Succeeded:  0
  * Total:      1
```

**Comment by gounthar** [comment]
I initially incorrectly blamed the Temurin API for the issue.

Damien helped me troubleshoot the problem through several steps:

1. We removed the `transformers` section from my manifest, which resolved the issue.
2. We tested the Adoptium API using [their Swagger UI](https://api.adoptium.net/q/swagger-ui/#/Version) and discovered that:
   - `21.0.5_11` returns a 400 HTTP error
   - `21.0.5+11` works correctly

3. When we restored the `transformers` section but removed only the `jdk-` prefix (leaving the `+` symbol unchanged), the manifest worked properly.

This investigation revealed that the error was in my manifest, not in the API. However, a more descriptive error message indicating that the requested version wasn't found would have helped direct my troubleshooting efforts more effectively.

### Feature Request
Could we enhance the error handling to provide more meaningful messages when the Temurin API returns an error code? This would help users identify potential issues in their condition statements more quickly.

Thank you for implementing this feature despite my initial misunderstanding.

**Comment by dduportal** [comment]
> I initially incorrectly blamed the Temurin API for the issue.
> 
> Damien helped me troubleshoot the problem through several steps:
> 
>     1. We removed the `transformers` section from my manifest, which resolved the issue.
> 
>     2. We tested the Adoptium API using [their Swagger UI](https://api.adoptium.net/q/swagger-ui/#/Version) and discovered that:
>        
>        * `21.0.5_11` returns a 400 HTTP error
>        * `21.0.5+11` works correctly
> 
>     3. When we restored the `transformers` section but removed only the `jdk-` prefix (leaving the `+` symbol unchanged), the manifest worked properly.
> 
> 
> This investigation revealed that the error was in my manifest, not in the API. However, a more descriptive error message indicating that the requested version wasn't found would have helped direct my troubleshooting efforts more effectively.
> ### Feature Request
> 
> Could we enhance the error handling to provide more meaningful messages when the Temurin API returns an error code? This would help users identify potential issues in their condition statements more quickly.
> 
> Thank you for implementing this feature despite my initial misunderstanding.

Reworked a bit the error output:

```
condition: condition#checkListOfPlatforms
------------------------------

ERROR: something went wrong in "condition#checkListOfPlatforms" : the version "17.0.13_11" is not a valid Temurin version.
API response was: "Got an HTTP error 400 from the API.\n"
```

WDYT?

**Review by gounthar — APPROVED** [review]
Looks good to me, thanks for the logs! 👍

**Review by olblak — APPROVED** [review]
Thanks for the pullrequest.
I test it and it works great

**Pull request merged**
