### PR TITLE
Re-design pullrequest managed by Updatecli

### LINKED ISSUE #1125: Feature Request: Redesign GitHub Pullrequest body
### Is your feature request related to a problem?

A pullrequeset created by Updatecli doesn't provide usefull information when it changes more than one target such as https://github.com/olblak/updatecli-app-dashboard/pull/34

The problem is different pipeline can reuse the same pipeline, some have changelog, others not. And finally a pullrequest can change different type of information.

### Solution you'd like

Using html means that we can "easily" parse existing pullrequest body. By using the tag "id" we can specify hidden information to identify to which pipeline the information is related

## Template

```
<body>

    <h2 id="<pipeline_spec_checksum>"> Pipeline Name</h2>
    <!-- I am wondering if adding a field description to the pipeline spec so we could display it here with additional information-->

    Show Pipeline Reports

    <!-- For each target in a manifest-->
    <details><summary id="<target1_spec_checksum>"><h3>Target One Name</h3></summary>
        <details><summary><h4>Changelog</h4></summary>
        
        <!-- I am wondering if adding a field description to the resource spec so we could display it here-->
        
        ```
            Changelog output
        ```
        </details>
    </details>

    <!-- For each target in a manifest-->
    <details><summary id="<target1_spec_checksum>"><h3>Target Two Name</h3></summary>
        <details><summary><h4>Changelog</h4></summary>
        
        <!-- I am wondering if adding a field description to the resource spec so we could display it here-->
        
        ```
            Changelog output
        ```
        </details>
    </details>

    <!-- Show disclaimer-->>
</body>
```

## Example

<h2 id="asdfasdfasd">Update Golang Version used</h2>
<details><summary><h3>Update Golang used by go.mod</h3></summary>
<details><summary><h4>Changelog</h4></summary>
 
 ```
   This release fix bug XxX
  ```

</details>
</details>

<details><summary><h3>Update Golang used in Dockerfile</h3></summary>
</details>

<details><summary><h3>Update Golang used in Hugo</h3></summary>
</details>

### Alternatives you've considered

Considering that GitHub pullrequest accept both Markdown and Html, I considered using directly Markdown but after some quick search it appears easier to parse html and only edit the correct information based on the ID than using Markdown

### Anything else?

As we know the structure of the body in advance, we could simply use a xml parser to parse existing pullrequest body

### PR DESCRIPTION
**Pull request by olblak**
Fix #1125 

This pullrequest refactors the amount of information provided by Updatecli when it opens a pullrequest from an "action".
The goal is to be able to provide information for each target. Until now, Each pullrequest created by Updatecli would only use information retrieved from the first target. The reason is due to the fact the Updatecli can open/update the same pullrequest from different execution or pipeline, and it doesn't store any state. This made it difficult to identify when Updatecli had to update a pullrequest. To solve this problem, Updatecli store now pullrequest in html code such as

```
<details id="xxx">
<details>
```
 
where xxx is a sha256 has generated from manifest information.
If a pullrequest already exist, then it tries to parse the pullrequest body to retrieve already stored information.

An example of pullrequest is available on https://github.com/olblak/epinio-helm-chart/pull/58  

## Test

To test this pull request, you can use any manifest that contains more that one target

```shell
cp <to_package_directory>
go test
```

### Tradeoff

To generate ID, I mainly use resource title hash both. The risk of collision is very minimal.

A pullrequest now shows all target associated to a pipeline no matter that it was changed or not. The reason is because there is no state, there is no way to identify across Updatecli execution when an information was modified.

### Potential improvement

* I am planning to enriched PR content by using information changed by target, for that I need to update the target interface and I am planning to open a different pullrequest for that purpose only.

* While looking at the gitea code, I noticed that scm relying on drone/go-scm doesn't support updating existing pullrequest. With the azure devops pullrequest, I realize that Updatecli needs are different, and only a subpart of drone/go-scm. I'll probably come with a similar but smaller library

* Now the pullrequest body are a bit more complex, the action interface needs a dryrun function to just show what would change

* Create action interface should be simplified

### CODE REVIEW

**Comment by olblak** [comment]
Worth mentioning I decided to drop the following information 

```
Source:
	✔ [chart] Get latest Rancher Helm Chart version(helmchart)


Condition:

Target:
	✔ [install] Update rancher/install.sh(file)
	✔ [manifest] Update rancher/manifest.yaml(yaml)
```

The reason is outside of show the pipeline, the information is uselss

**Comment by olblak** [comment]
While outside the scope of this PR, I am wondering if showing the pipeline using mermaidjs would be interesting

**Comment by lemeurherve** [comment]
Do you have a pull request open somewhere with the current result?

I find https://github.com/olblak/epinio-helm-chart/pull/52 too heavy and with many duplications, not sure if it's reflecting the current state of this PR.

**Comment by dduportal** [comment]
As per https://github.com/olblak/epinio-helm-chart/pull/52, it looks unusable at all. It's not clear to me what is the intent.

Please don't merge this PR without a full discussion and agreement.

**Comment by olblak** [comment]
A simple example, with one pullrequest opened by one pipeline containing one target
* https://github.com/olblak/updatecli/pull/222
<details><summary> raw html</summary>

```
<Actions>
    <action id="288309dfdc93af4a62c54e588aecc0383d215f0b34fbce9a0c10614df3798f8a">
        <h3>[updatecli] Bump golangci-lint version to v1.52.2</h3>
        <details id="37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f">
            <summary>Update Golangci-lint version to v1.52.2</summary>
            <details>
                <summary>v1.52.2</summary>
                <pre>&#xA;Release published on the 2023-03-25 18:30:47 +0000 UTC at the url https://github.com/golangci/golangci-lint/releases/tag/v1.52.2&#xA;&#xA;## Changelog&#xA;* da04413a build(deps): bump github.com/moricho/tparallel from 0.3.0 to 0.3.1 (#3719)&#xA;* 1f4fed7c fix(pre-commit): require_serial &amp; pass_filenames (#3713)&#xA;&#xA;</pre>
            </details>
        </details>
    </action>
</Actions>

```

</details>

A pullrequest opened by seven pipelines (seven different manifest generated by autodiscovery)
https://github.com/olblak/epinio-helm-chart/pull/58

some changes:

* If the PR is updated after a new commit bumping once again to  a newer version, the changelog will append the new version instead of replacing the existing one

**Comment by dduportal** [comment]
> A simple example, with one pullrequest opened by one pipeline containing one target
>
>    https://github.com/olblak/updatecli/pull/222

That one is really nice and meet my desiderata ❤️ 

I'm trying a bit of exploration to explain my upcoming nitpicks on the design.

I'll also try to focus on the "multi actions" to help as much as I can.

First "draft": https://github.com/dduportal/updatecli/issues/27 (case of single dependency)

**Comment by olblak** [comment]
> That one is really nice and meet my desiderata heart

Thanks for the feedback, I'll wait until the next weekend, and then I'll triggered a release with this change only.
Even thought I did a lot of testing, I would like to see how it behaves in the real world while being able to easily rollback

My main concern is to have a pullrequest that evolves over time with duplication such as https://github.com/olblak/epinio-helm-chart/pull/52

Now that I think about it, I should probably also add the Updatecli version within the pullrequest metadata

**Comment by olblak** [comment]
Tested on Gitlab and Gitea and all works good

**Pull request merged**
