### PR TITLE
Fix parent target execution

### PR DESCRIPTION
**Pull request by macedogm**
Fix https://github.com/updatecli/updatecli/issues/983

## Test

N/A

### Tradeoff

N/A

### Potential improvement

N/A

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Review by lemeurherve — APPROVED** [review]
LGTM, thanks for the detailed issue and the fix!

**Review by dduportal — APPROVED** [review]
That is a nice catch, thanks for this fix!

**Comment by dduportal** [comment]
Ping @olblak can we let you merge based on how you want to release next versions?

**Comment by olblak** [comment]
Thanks for the PR and the reviews.
I am ready to merge this PR
Regarding a new release, we  can either trigger a release now or wait until the weekend.
Unless @macedogm the current bug affect you, I would prefer waiting for the weekend :)

**Review by olblak — APPROVED** [review]

**Pull request merged**
