### PR TITLE
fix(pullrequest): default title with the source output instead of its result '✔'

### PR DESCRIPTION
**Pull request by lemeurherve**
Fix 
image

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

### Potential improvement

I intend to improve this pull request default title by including the name of what's updated, and maybe also the type.

Something like

> [updatecli] Bump `<name>` <helm chart|docker image|...> version to <source-output>

The easiest way I found to retrieve the name would be to use sources[0].name, implying the change of (jenkins infra) manifests (they almost all have a description in the `name` field)

### CODE REVIEW

**Comment by olblak** [comment]
> I intend to improve this pull request default title by including the name of what's updated, and maybe also the type.
I think it would only work if the pullrquest only depends on one source. Otherwise it can be confusing.

**Review by olblak — APPROVED** [review]
Nice catch, I am surprised that this bug lived for so long :o

**Comment by lemeurherve** [comment]
> I think it would only work if the pullrquest only depends on one source. Otherwise it can be confusing.

Yes there will be special cases, I intend to respond to the common cases mainly, like one source, and fallback to a default title like the current one otherwise.

**Comment by olblak** [comment]
> > I think it would only work if the pullrquest only depends on one source. Otherwise it can be confusing.
> 
> Yes there will be special cases. I intend to respond to the common cases mainly (like one source) and fallback to a default title like the current one otherwise.

Is this something you want to implement in this PR?
Imho the current one is ready to be ship, I am planning to trigger a release next week

**Comment by lemeurherve** [comment]
> Is this something you want to implement in this PR?

No. 🚢

**Pull request merged**
