### PR TITLE
Fix commit message when there is 2 or more commits for the same PR

### PR DESCRIPTION
**Pull request by macedogm**
Fixes https://github.com/updatecli/updatecli/issues/1004 and https://github.com/updatecli/updatecli/issues/1005

## Test

See the steps to reproduce described in each issue.

### Potential improvement

Perhaps the variable `placeholders` can have a better name.

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Comment by olblak** [comment]
Thanks for the PR, I am just waiting @dduportal review as he's currently looking into the scm part :)

**Comment by olblak** [comment]
I suspect that the function is call in a test file hence the linting error

**Comment by macedogm** [comment]
I totally missed the test file. I've updated it now and tests are passing.

However, I see that it's still throwing an error, which also happens before the changes made.

```
% go test                                                                                 
ERRO[0000] error: empty commmit messager                
PASS
ok  	github.com/updatecli/updatecli/pkg/plugins/scms/git/commit	0.617s
```

Unfortunately I wasn't able to clean this error, I might have missed something simple.

**Review by dduportal — APPROVED** [review]
LGTM thanks a lot!

**Pull request merged**
