### PR TITLE
Test updatecli on windows && macos runner

### PR DESCRIPTION
**Pull request by olblak**
Signed-off-by: Olblak <me@olblak.com>

Add Windows runner to test Golang

## Test
/

### Tradeoff

/

### Potential improvement
/

### CODE REVIEW

**Comment by olblak** [comment]
Well as I initially thought, it will take more time to fix the tests on Windows.
The good thing I now have access to a windows machine

**Comment by dduportal** [comment]
> Well as I initially thought, it will take more time to fix the tests on Windows. The good thing I now have access to a windows machine

Important note about this change:

- Unit test does NOT need to be run on all platforms. If it fails on a platform, then it has to be either refactored to NOT depend on a platform or moved as an end to end test. Even integration tests should not be dependent otherwise it means both them and the code they test is fragile.
- WDYT about running only end to end tests on different paltforms, and staging the built `updatecli` binary between the build machine and the others
  - No need to setup golang and build on each machine
  - spend less time and machine cycle on tests that would have low value

**Comment by olblak** [comment]
Thanks for your feedback 

> WDYT about running only end to end tests on different paltforms, and staging the built updatecli binary between the build machine and the others

Yep that's something which I am considering and **should** be easier to implement.

> Unit test does NOT need to be run on all platforms. If it fails on a platform, then it has to be either refactored to NOT depend on a platform or moved as an end to end test. Even integration tests should not be dependent otherwise it means both them and the code they test is fragile.
 
> If it fails on a platform, then it has to be either refactored to NOT depend on a platform or moved as an end to end test.

I agree with you, but running the tests on all platform is a good way to catch tests that should be refactored to not be platform specific.

I now have access to Windows machine  so I am planning to do some experimentation

**Comment by olblak** [comment]
Closing for now, I managed to build a Dev environment on a windows machine so I'll rework this effort from there

**Pull request closed without merging**
