### PR TITLE
Fix working

### PR DESCRIPTION
**Pull request by olblak**
Fix working

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
Good catch !

**Comment by lemeurherve** [comment]
I'd like to deserve a medal for the least meaningful PR title and body though ^^

**Comment by lemeurherve** [comment]
> > I'd like to deserve a medal for the least meaningful PR title and body though ^^
> 
> I wanted to say "fix wording" :-D

Even better ^^

**Comment by dduportal** [comment]
> > > I'd like to deserve a medal for the least meaningful PR title and body though ^^
> > 
> > 
> > I wanted to say "fix wording" :-D
> 
> The typo in the typo fix, even better ^^

🦆 autocorrect :trollface:

**Pull request merged**
