### PR TITLE
Allow multiple query combined with versionfilter to json source

### PR DESCRIPTION
**Pull request by olblak**
Signed-off-by: Olblak <me@olblak.com>

As discussed on https://github.com/updatecli/updatecli/issues/942#issuecomment-1284561424
I realized that it would be super usefull to be able to do a multiple query combined with versionfilter on the json resource

This pullrequest allows the following manifest to work 

```
sources:
  semverVersion:
    kind: json
    name: Get latest version from remote json file
    spec:
      file: https://api.github.com/repos/updatecli/updatecli/releases
      key: ".[*].tag_name"
      multiple: true
      versionfilter:
        kind: semver
        pattern: "v0.35"
```

## Example 

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "/tmp/updatelci.yaml"

SCM repository retrieved: 0


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



##################
# UPDATELCI.YAML #
##################


SOURCES
=======

semverVersion
-------------
Searching for version matching pattern "v0.35"
✔ Value "v0.35.1", found in file "https://api.github.com/repos/updatecli/updatecli/releases", for key ".[*].tag_name"'

=============================

REPORTS:


- UPDATELCI.YAML:
	Source:
		✔ [semverVersion] Get latest version from remote json file (kind: json)

Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	0
  * Skipped:	1
  * Succeeded:	0
  * Total:	1

```

## Test

To test this pull request, you can run the following commands:

```shell
go build -o bin/updatecli .
./bin/updatecli --config manifest_mentioned_here.yaml
go test
```

### Potential improvement

I'll try to find some time to open a similar pullrquest for toml and csv as they also use Dasel
I need to investigate for the xml resource but it should be possible
Unfortunately, it won't work for the yaml resource as it doesn't support multiple query

### CODE REVIEW

**Comment by dduportal** [comment]
Like in https://github.com/updatecli/updatecli/issues/945#issuecomment-1285044879, it seems that this would be a broader change as it implies having a multi-valued source.

How is the order managed?

**Comment by dduportal** [comment]
Can you update the PR description to show the result? The example is not clear on what is it doing exactly?

**Comment by olblak** [comment]
> Like in [#945 (comment)](https://github.com/updatecli/updatecli/issues/945#issuecomment-1285044879), it seems that this would be a broader change as it implies having a multi-valued source.

The source output doesn't change as we still return one single value. Here `versionfilter` works the same way than for plugins

- githubrelease
- giteaTag
- gittag
- dockerimage

Basically we retrieve a list of information and we delegate the responsability to the versionfilter to identify the value we are looking for

So this pullrequest introduced two parameters

1. `multiple`: It's used to describe that we are looking for multiple values from the json query and not only one. Because `.[*].tag_name` is a valid json key identifer
1. `versionfilter`: It's used to filter the result from the multiple query 

In the context of a source, both must be used together

**Comment by olblak** [comment]
> Can you update the PR description to show the result? The example is not clear on what is it doing exactly?

I added an example in the PR body

**Comment by olblak** [comment]
I am open to change if it makes things clearier. Ideally I would like to use the same wording for csv/toml/xml/json/yaml
Maybe @hervelemeur has some opinion too

**Comment by olblak** [comment]
Before merging I need to correctly deprecate the key `multiple` previously used for conditoin and target

**Pull request merged**
