### PR TITLE
Use vmware-labs/yaml-jsonpath for yaml path

### PR DESCRIPTION
**Pull request by mavimo**
Fix #XXX

This PR swap the implementation used for parse yamlpath to https://github.com/vmware-labs/yaml-jsonpath/ that support

## Test

To test this pull request, you can run the following commands:

```shell
cd pkg/plugins/resources/yaml/
go test
```

### Tradeoff

Swap from https://github.com/go-yaml/yaml to https://pkg.go.dev/gopkg.in/yaml.v3

### Potential improvement

Increase test coverage
Code cleanup

### CODE REVIEW

**Comment by olblak** [comment]
Thanks for the pullrequest, I wasn't aware of this library.
It would definitely be a great addition to Updatecli as we would be able to specify more robust yaml key by using advanced yamlpath queries.
My only concern is moving back to a library that relies on go-yaml/yaml means we would reopen some limitations. Like a document with multiple `---` or unicode in the yaml document 

Both libraries https://github.com/goccy/go-yaml and https://github.com/go-yaml/yaml have pro and cons
I need to do additional testing to better understand them.

I'll soon be fully available

**Comment by mavimo** [comment]
@olblak thx for the feedback, is the same doubt that I have, in the meantime I start to investigate if I can try to create a variant of the yaml-jsonpath library that work on the AST produced by `[goccy/go-yaml](https://github.com/goccy/go-yaml)`...

**Comment by olblak** [comment]
> @olblak thx for the feedback, is the same doubt that I have, in the meantime I start to investigate if I can try to create a variant of the yaml-jsonpath library that work on the AST produced by `[goccy/go-yaml](https://github.com/goccy/go-yaml)`...

I am curious how much effort would be needed.

**Comment by mavimo** [comment]
@olblak not trivial but doable (I expect a couple of days of works plus the time to integrate it.

If you think is the best way I'll try to find some time to make it happen..

**Comment by olblak** [comment]
What would you think to have a flag to either enable the `default` or `yamlpath` where `default` is the current situation using goccy library and `yamlpath` would rely on your PR

My reasoning is both `goccy/go-yaml` and `vmware-labs/yaml-jsonpath` have major limitation and both can still improve independently.

That being said `vmware-labs/yaml-jsonpath` is used by many large project like Tanzu, Kubernetes, or devspace which is a good sign

Let me tests how the current PR behaves by the various issues by the move to goccy

**Comment by olblak** [comment]
As expected, after a quick test, this issue would reopen: 

* Fix https://github.com/updatecli/updatecli/issues/522
* Fix https://github.com/updatecli/updatecli/issues/1028
* Fix https://github.com/updatecli/updatecli/issues/903

**Comment by olblak** [comment]
After some test with the new jsonpath, it's really a great, and it would make many pipeline more robust, especially when manipulating arrays. 

In the current situation, I think both implementation make sense

**Comment by olblak** [comment]
I opened a PR on your fork https://github.com/mavimo/updatecli/pull/1/files with the fix I needed

**Comment by mavimo** [comment]
@olblak added your suggestion + rebased

**Comment by olblak** [comment]
closing in favor of https://github.com/updatecli/updatecli/pull/1741

**Pull request closed without merging**
