### PR TITLE
chore: more compact footer template

### LINKED ISSUE #1308: Feature Request: PR description a bit too verbose
### Is your feature request related to a problem?

Recent changes in the PR description are a bit too verbose

image

### Solution you'd like

I like the project and I think it's important to provide visibility but I wonder whether the information unrelated to the changes but the healthy of the project could be a bit less verbose

### Alternatives you've considered

https://github.com/updatecli/updatecli/blob/27aeab45b52538c44edb9d3730f316a1e0ce7c75/pkg/plugins/utils/action/main.go#L32-L40 could be in a collapse section

Though It might hide information that can benefit the updatecli ecosystem so people can engage easily by having those details in the PR itself. 

### Anything else?

We also use `mergify` and it uses `Mergify commands and options` to show all the details, see https://github.com/elastic/apm-server/pull/10686

I don't know whether that could be something sensible or maybe it hides things a bit too much.

Thanks for this project!

### PR DESCRIPTION
**Pull request by lemeurherve**
Fix #1308 

More compact footer and small rewording like *Action triggered by Updatecli* > *Created by Updatecli*

### Before:
image

### After:
image

Open:
image

## Test

N/A

### Tradeoff

N/A

### Potential improvement

See comment below: https://github.com/updatecli/updatecli/pull/1316#issuecomment-1533436926

## Example

<table>
  <tr>
    <td width="77">
      Updatecli logo
    </td>
    <td>
      <p>
        Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
      </p>
      <details><summary>Options:</summary>
        <br />
        <p>Most of Updatecli configuration is done via Updatecli manifest(s).</p>
        <ul>
          <li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
          <li>If you close this pull request and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
        </ul>
        <p>
          Feel free to report any issues at <a href="https://github.com/updatecli/updatecli/issues">github.com/updatecli/updatecli</a>.<br />
          If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, and/or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
        </p>
      </details>
    </td>
  </tr>
</table>

### CODE REVIEW

**Comment by lemeurherve** [comment]
cc @v1v, WDYT?

**Comment by lemeurherve** [comment]
If the `<table>` syntax isn't supported elsewhere than GitHub, I propose this as an alternative with Markdown table:

---
| Updatecli logo| Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>|
|---|---|

<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via Updatecli manifest(s).</p>
<ul>
<li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pull request and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>

Feel free to report any issues at <a href="[https://github.com/updatecli/updatecli/issues](https://github.com/updatecli/updatecli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)">updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
</details>

**Comment by olblak** [comment]
Thanks for the pullrequest, I just tested on Gitlab and Gitea and it works great.
I am waiting for @v1v feedback before merging

**Review by v1v — DISMISSED** [review]
That's great, I like that and thanks for this! ❤️

**Review by olblak — APPROVED** [review]

**Pull request merged**
